---
title: "R-4.4.1-Quarto_Website_Example"
---

This is a Quarto website.

To learn more about Quarto websites visit <https://quarto.org/docs/websites>.

```{r}
1 + 1
```

```{r}
#| label: fig-petct
#| fig-cap: "2023년도 FDG PET/CT 건수"
#| echo: false

library(rjson)
library(httr)
library(plyr)

download_api_data <- function() {
  base_url <- "http://apis.data.go.kr/B551182/mdlrtActionInfoService"
  call_url <- "getMdlrtActionByClassesStats"
  method <- "GET"
  My_API_Key <- "DRwFWZ/jfi6551teJKgRhkKgC+XhcjobN+ccY2MQdF9yZdx8xL5Kn4IljljMCWGsl2ObEco/rm21r14CN7iG0g=="  # 실제 API 키
  params <- list(
    serviceKey = My_API_Key,
    pageNo = 1,
    numOfRows = 10,
    resultType = "json",
    year = "2023",
    stdType = "1",
    st5Cd = "HK010"
  )
  
  # API 호출
  url <- paste0(base_url, "/", call_url)
  response <- GET(url, query = params)

  if (status_code(response) == 200) {
    json_text <- content(response, as = "text")
    data <- fromJSON(json_text)
    return(data)
  } else {
    print(paste("API 호출 실패:", status_code(response)))
    return(NULL)
  }
}

data <- download_api_data()
data_list<-data$response$body$items$item
df <- rbind.fill(lapply(data_list, as.data.frame))

barplot(df$totUseQty, 
        names.arg = df$diagCdNm)  # x축 레이블 설정
```